version: "3"

services:
    webserver:
        build: ./bin/webserver
        container_name: 'php7.4_apache_webserver'
        ports: 
            - "8009:80"
        volumes:
            - ./www:/var/www/html/
        networks:
            - default
            
    mysql:
        build: ./bin/mysql
        container_name: 'mysql_docker'
        hostname: 'mysql_docker'
        # restart: 'always'
        ports:
            - "3307:3306"
        volumes:
            - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
            - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: docker_db
            MYSQL_USER: user
            MYSQL_PASSWORD: password


    phpmyadmin:
        build: ./bin/phpmyadmin
        container_name: 'phpmyadmin_docker'
        networks:
            - default
        links:
            - mysql
        environment:
            PMA_HOST: mysql
        ports:
            - '8010:80'
        volumes:
            - /sessions


